### ISSUE TITLE
desktop image does not support `snap` or installing web browsers

### ISSUE THREAD

**Issue by bpmct** [cdr/enterprise-images#288]
Can we make it a bit more featureful? @matifali 

```sh
sudo apt-get install firefox
```

then

```sh
firefox
```

does not work.

**Comment by matifali** [comment]
I will look into it. Thank you for the feedback.

**Comment by matifali** [comment]
It looks like getting `snapd` in a Docker container is not as straightforward as it requires `systemd`, which needs `sysbox-runc`. 
https://forums.docker.com/t/snap-in-dockerfile/136997/2

**Comment by matifali** [comment]
Yes. I am working on supporting kasm images.
