### ISSUE TITLE
How do I enable jupyterlab extensions?

### ISSUE THREAD

**Issue by m-miyagi-ps** [cdr/enterprise-images#32]
How do I enable jupyterlab extensions?
When I try to install extensions, I get the following error and cannot install.

`Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).`

I tried installing miniconda and installing nodejs with conda, but I couldn't solve the problem.

`sudo apt update && sudo apt install nodejs npm`
![error](https://user-images.githubusercontent.com/62577470/98676404-e9d83e00-239e-11eb-8aad-fa2f87335a5c.png)

**Comment by vapurrmaid** [comment]
Hey @m-miyagi-ps did you run into this when using https://hub.docker.com/r/codercom/enterprise-jupyter ?
