### ISSUE TITLE
codercom/enterprise-goland not rendering GoLand

### ISSUE THREAD

**Issue by ericpaulsen** [cdr/enterprise-images#66]
Customer reported that when creating a Workspace from `enterprise-goland`, it does not render GoLand in the Applications section of the dashboard. I've replicated this myself in `demo.cdr.dev`. If someone could investigate, that'd be great. Thanks!

**Comment by vapurrmaid** [comment]
> Customer reported that when creating a Workspace from `enterprise-goland`, it does not render GoLand in the Applications section of the dashboard. I've replicated this myself in `demo.cdr.dev`. If someone could investigate, that'd be great. Thanks!

@ericpaulsen - what version of Coder?

**Comment by ericpaulsen** [comment]
1.18.1

**Comment by jawnsy** [comment]
I could was not able to reproduce this with Coder v1.19.0 and enterprise-goland

![image](https://user-images.githubusercontent.com/52710/119231013-91af9080-bad3-11eb-84d4-94f91b3960c6.png)

Are you still able to reproduce this problem? What does "not rendering" mean in this context?

**Comment by ericpaulsen** [comment]
"Not rendering" meaning that the GoLand icon was not displaying in the Applications section of the dashboard. Oddly enough, I just tested once again on demo.cdr.dev (v1.18.1), and could not reproduce the issue. GoLand rendered just fine. Closing this out.

Thanks for following up @jawnsy.
